name: tuple
version: 0.1.1
author: Boris Kaul <localvoid@gmail.com>
description: Tuple data structure
homepage: https://github.com/localvoid/tuple
environment:
  sdk: '>=1.6.0'
dev_dependencies:
  test: any
